# Generated by Django 5.2.1 on 2025-06-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_alter_comment_options_and_more'),
        ('blog', '0004_auto_20250605_2244'),
    ]

    operations = [
    ]
